package com.example

import com.example.models.SpoofProfile

object FridaInjector {

    fun generateFridaScript(profile: SpoofProfile): String {
        return """
            |/*
            | * Device Spoofing Hook Script - Generated by Device Cloner
            | * Target Profile: ${profile.profileName}
            | * Designed for integration with Frida-Gadget or Frida-Server.
            | */
            |
            |Java.perform(function () {
            |    console.log("[+] Frida Script Loaded Successfully!");
            |    console.log("[+] Intercepting and Spoofing Device Identity as: ${profile.brand} ${profile.model}");
            |
            |    // ---- 1. SPOOF TELEPHONY DATA ----
            |    var TelephonyManager = Java.use("android.telephony.TelephonyManager");
            |
            |    if (TelephonyManager) {
            |        console.log("[*] Registering Hooks for TelephonyManager...");
            |        
            |        // Spoof IMEI / Device ID
            |        var getDeviceIdOverload = TelephonyManager.getDeviceId.overloads;
            |        for (var i = 0; i < getDeviceIdOverload.length; i++) {
            |            getDeviceIdOverload[i].implementation = function () {
            |                console.log("[TelephonyManager] getDeviceId() Spoofed -> ${profile.imei}");
            |                return "${profile.imei}";
            |            };
            |        }
            |
            |        // Spoof Sim Serial
            |        TelephonyManager.getSimSerialNumber.implementation = function () {
            |            console.log("[TelephonyManager] getSimSerialNumber() Spoofed -> ${profile.simSerial}");
            |            return "${profile.simSerial}";
            |        };
            |
            |        // Spoof Network Operator Name
            |        TelephonyManager.getNetworkOperatorName.implementation = function () {
            |            console.log("[TelephonyManager] getNetworkOperatorName() Spoofed -> ${profile.simOperator}");
            |            return "${profile.simOperator}";
            |        };
            |
            |        // Overloads for Newer APIs
            |        try {
            |            TelephonyManager.getImei.overload().implementation = function () {
            |                console.log("[TelephonyManager] getImei() Spoofed -> ${profile.imei}");
            |                return "${profile.imei}";
            |            };
            |            TelephonyManager.getImei.overload("int").implementation = function (slotId) {
            |                console.log("[TelephonyManager] getImei(slotId) Spoofed -> ${profile.imei}");
            |                return "${profile.imei}";
            |            };
            |        } catch (e) {
            |            console.log("[-] Older device; getImei method override skipped: " + e);
            |        }
            |    }
            |
            |    // ---- 2. SPOOF SETTINGS.SECURE (ANDROID_ID) ----
            |    var SettingsSecure = Java.use("android.provider.Settings${'$'}Secure");
            |    if (SettingsSecure) {
            |        console.log("[*] Registering Hooks for Settings.Secure...");
            |
            |        SettingsSecure.getString.implementation = function (resolver, name) {
            |            if (name === "android_id") {
            |                console.log("[Settings.Secure] getString(android_id) Intercepted -> ${profile.androidId}");
            |                return "${profile.androidId}";
            |            }
            |            return this.getString(resolver, name);
            |        };
            |    }
            |
            |    // ---- 3. SPOOF WIFI INFO ----
            |    var WifiInfo = Java.use("android.net.wifi.WifiInfo");
            |    if (WifiInfo) {
            |        console.log("[*] Registering Hooks for WifiInfo...");
            |        
            |        WifiInfo.getMacAddress.implementation = function () {
            |            console.log("[WifiInfo] getMacAddress() Intercepted -> ${profile.wifiMac}");
            |            return "${profile.wifiMac}";
            |        };
            |
            |        WifiInfo.getSSID.implementation = function () {
            |            console.log("[WifiInfo] getSSID() Intercepted -> \"${profile.ssid}\"");
            |            return "\"${profile.ssid}\"";
            |        };
            |    }
            |
            |    // ---- 4. SPOOF OS BUILD PROPERTIES ----
            |    var BuildField = Java.use("android.os.Build");
            |    if (BuildField) {
            |        console.log("[*] Spoofing android.os.Build reflective fields...");
            |        
            |        // Hook the Field values directly via reflection or properties
            |        setStaticField(BuildField, "BRAND", "${profile.brand}");
            |        setStaticField(BuildField, "MODEL", "${profile.model}");
            |        setStaticField(BuildField, "MANUFACTURER", "${profile.manufacturer}");
            |        setStaticField(BuildField, "DEVICE", "${profile.device}");
            |        setStaticField(BuildField, "PRODUCT", "${profile.product}");
            |        setStaticField(BuildField, "BOARD", "${profile.board}");
            |        setStaticField(BuildField, "HARDWARE", "${profile.hardware}");
            |        setStaticField(BuildField, "FINGERPRINT", "${profile.fingerprint}");
            |        setStaticField(BuildField, "ID", "${profile.buildId}");
            |    }
            |});
            |
            |function setStaticField(clazz, fieldName, value) {
            |    try {
            |        var field = clazz.class.getDeclaredField(fieldName);
            |        field.setAccessible(true);
            |        field.set(null, value);
            |        console.log("[BuildSpoof] Set static field " + fieldName + " -> " + value);
            |    } catch (e) {
            |        console.log("[-] Failed to set Build field " + fieldName + ": " + e);
            |    }
            |}
        """.trimMargin()
    }
}
